# Generated by Django 5.0.6 on 2026-06-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='started_preparing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
