# Generated by Django 5.0.6 on 2026-07-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0002_order_started_preparing_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill_requested',
            field=models.BooleanField(default=False),
        ),
    ]
